Defer client connection until someone needs it.
Otherwise, it is not possible to save global config with incorrect connection details:

javax.servlet.ServletException: java.lang.NullPointerException
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:719)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:770)
        at org.kohsuke.stapler.Stapler.invoke(Stapler.java:583)
        at org.kohsuke.stapler.Stapler.service(Stapler.java:214)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:491)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1074)
        at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:95)
        at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:87)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
        at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
        at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
        at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
        at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
        at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:50)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
        at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:365)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:185)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:689)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:391)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:146)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
        at org.mortbay.jetty.Server.handle(Server.java:285)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:457)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:765)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:628)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:209)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:357)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:329)
        at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:475)
Caused by: java.lang.NullPointerException
        at org.apache.xmlrpc.client.XmlRpcCommonsTransport.newPostMethod(XmlRpcCommonsTransport.java:100)
        at org.apache.xmlrpc.client.XmlRpcCommonsTransport.initHttpHeaders(XmlRpcCommonsTransport.java:87)
        at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:142)
        at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
        at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
        at com.github.vjuranek.beaker4j.xmlrpc.client.BeakerXmlRpcClient.doRPCall(BeakerXmlRpcClient.java:54)
        at com.github.vjuranek.beaker4j.xmlrpc.client.BeakerXmlRpcClient.doRPCall(BeakerXmlRpcClient.java:47)
        at com.github.vjuranek.beaker4j.xmlrpc.client.BeakerXmlRpcClient.execute(BeakerXmlRpcClient.java:43)
        at com.github.vjuranek.beaker4j.xmlrpc.client.BeakerXmlRpcClient.authenticate(BeakerXmlRpcClient.java:20)
        at com.github.vjuranek.beaker4j.remote_model.Identity.authenticate(Identity.java:60)
        at com.github.vjuranek.beaker4j.remote_model.Identity.authenticate(Identity.java:56)
        at org.jenkinsci.plugins.beakerbuilder.BeakerBuilder$DescriptorImpl.setupClient(BeakerBuilder.java:390)
        at org.jenkinsci.plugins.beakerbuilder.BeakerBuilder$DescriptorImpl.configure(BeakerBuilder.java:380)
        at jenkins.model.Jenkins.configureDescriptor(Jenkins.java:2773)
        at jenkins.model.Jenkins.doConfigSubmit(Jenkins.java:2736)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:288)
        at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:151)
        at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:90)
        at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:111)
        at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
        at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:677)
        ... 35 more